In [16]:
import pandas as pd
import numpy as np
import sklearn.model_selection as model_selection
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [17]:
data=pd.read_csv('Social_Network_Ads.csv')
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [18]:
real_x=data.iloc[:,[2,3]].values
real_y=data.iloc[:,4].values

In [20]:
training_x,test_x,training_y,test_y=model_selection.train_test_split(real_x,real_y,test_size=0.25,random_state=0)

In [21]:
s_c=StandardScaler()
training_x=s_c.fit_transform(training_x)
test_x=s_c.fit_transform(test_x)
test_x

array([[-0.54748976,  0.5130727 ],
       [ 0.15442019, -0.61825566],
       [-0.10879604,  0.14615539],
       [-0.54748976,  0.26846116],
       [-0.10879604, -0.61825566],
       [-0.81070599, -1.53554892],
       [-0.45975102, -1.68843113],
       [-0.0210573 ,  2.25592989],
       [-1.60035469, -0.0678797 ],
       [ 0.94406888, -0.83229075],
       [-0.54748976, -0.6488321 ],
       [-0.72296725, -0.46537345],
       [ 0.06668145, -0.46537345],
       [ 0.24215893,  0.20730828],
       [-1.4248772 ,  0.48249625],
       [-0.37201227,  1.43036596],
       [ 0.06668145,  0.20730828],
       [-1.51261594,  0.45191981],
       [ 1.64597884,  1.8278597 ],
       [-0.10879604, -1.47439603],
       [-0.10879604, -0.70998498],
       [ 0.94406888,  2.25592989],
       [ 0.41763642, -0.58767922],
       [ 0.94406888,  1.06344865],
       [-1.16166097, -1.29093738],
       [ 1.11954637,  2.16420057],
       [-0.72296725,  0.5130727 ],
       [-0.63522851,  0.2990376 ],
       [ 0.06668145,

In [4]:
import sklearn.ensemble as ensemble

In [5]:
clf=ensemble.RandomForestClassifier(n_estimators=100,oob_score=True)

In [26]:
clf.fit(training_x,training_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=True, random_state=None, verbose=0,
                       warm_start=False)

In [29]:
pred_y=clf.predict(test_x)
pred_y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1])

In [30]:
clf.predict_proba(test_x)

array([[0.9 , 0.1 ],
       [0.99, 0.01],
       [0.97, 0.03],
       [1.  , 0.  ],
       [0.98, 0.02],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.02, 0.98],
       [1.  , 0.  ],
       [0.1 , 0.9 ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.93, 0.07],
       [1.  , 0.  ],
       [0.07, 0.93],
       [0.62, 0.38],
       [1.  , 0.  ],
       [0.11, 0.89],
       [0.99, 0.01],
       [0.98, 0.02],
       [0.4 , 0.6 ],
       [0.99, 0.01],
       [0.07, 0.93],
       [1.  , 0.  ],
       [0.36, 0.64],
       [0.94, 0.06],
       [0.96, 0.04],
       [1.  , 0.  ],
       [0.93, 0.07],
       [0.99, 0.01],
       [0.91, 0.09],
       [0.09, 0.91],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.99, 0.01],
       [1.  , 0.  ],
       [0.02, 0.98],
       [0.94, 0.06],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.99, 0.01],
       [0.25, 0.75],
       [1.  , 0.  ],
       [0.92, 0.08],
       [0.27,

In [31]:
from sklearn.metrics import confusion_matrix

In [33]:
c_m=confusion_matrix(test_y,pred_y)
c_m

array([[64,  4],
       [ 3, 29]])

In [1]:
pd.Series(clf.feature_importances_,index=training_x.columns).sort_values(ascending=False)

NameError: name 'pd' is not defined

In [49]:
clf.oob_score_

0.87

In [85]:
for i in [100,200,300]:
    clf=ensemble.RandomForestClassifier(n_estimators=i,oob_score=True,n_jobs=-1)
    clf.fit(training_x,training_y)
    print("oob score for {} tree is {}".format(i,clf.oob_score_))

oob score for 100 tree is 0.88
oob score for 200 tree is 0.8933333333333333
oob score for 300 tree is 0.88


In [2]:
import sklearn.metrics as metrics

In [3]:
metrics.roc_auc_score(test_y,pred_y)

NameError: name 'test_y' is not defined

In [4]:
for i in [100,200,300]:
    clf=ensemble.RandomForestClassifier(n_estimators=i,oob_score=True,n_jobs=-1)
    clf.fit(training_x,training_y)
    pred_oob=clf.oob_decision_function_[:,1]
    auc=metrics.roc_auc_score(test_y,pred_y)
    print("auc score for {} tree is {}".format(i,auc))

NameError: name 'ensemble' is not defined

In [90]:
result=pd.DataFrame({'actual':test_y,'predicted':pred_y})

In [92]:
result.head(10)

actual  predicted
0       0          0
1       0          0
2       0          0
3       0          0
4       0          0
5       0          0
6       0          0
7       1          1
8       0          0
9       0          1